//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "setcookie.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string setcookie::genText(const DrTemplateData& setcookie_view_data)
{
	drogon::OStringStream setcookie_tmp_stream;
	std::string layoutName{""};
	setcookie_tmp_stream << "<!DOCTYPE html>\n";
	setcookie_tmp_stream << "<html>\n";
	setcookie_tmp_stream << "<head>\n";
	setcookie_tmp_stream << "<title>";
{
    auto & val=setcookie_view_data["title"];
    if(val.type()==typeid(const char *)){
        setcookie_tmp_stream<<*any_cast<const char *>(&val);
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        setcookie_tmp_stream<<*any_cast<const std::string>(&val);
    }
}
	setcookie_tmp_stream << "</title>\n";
	setcookie_tmp_stream << "</head>\n";
	setcookie_tmp_stream << "<body>\n";
if(gotSet == true)
{
	setcookie_tmp_stream << "Your cookie got set! Congratulations!\n";
} else {
	setcookie_tmp_stream << "Somehow we couldnt set your cookie! :(\n";
}
	setcookie_tmp_stream << "</body>\n";
	setcookie_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(setcookie_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = setcookie_view_data;
auto str = std::move(setcookie_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
