//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class setcookie:public drogon::DrTemplate<setcookie>
{
public:
	setcookie(){};
	virtual ~setcookie(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
